# Generated by Django 5.1.6 on 2025-03-06 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('artifact_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '게시됨'), ('hidden', '숨김'), ('deleted', '삭제됨')], default='published', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feeds.feed')),
            ],
            options={
                'db_table': 'feed_images',
                'ordering': ['order'],
            },
        ),
    ]
