# Generated by Django 5.2 on 2025-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='view_count',
        ),
    ]
