# Generated by Django 5.1.6 on 2025-03-06 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_year', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('auto_generated', '자동 생성됨'), ('verified', '검증됨'), ('featured', '주목할 만한'), ('rejected', '거부됨')], default='auto_generated', max_length=20)),
                ('image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artifacts',
            },
        ),
        migrations.CreateModel(
            name='ArtifactFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_feeds', to='artifacts.artifact')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_artifacts', to='feeds.feed')),
            ],
            options={
                'db_table': 'artifact_feeds',
                'unique_together': {('artifact', 'feed')},
            },
        ),
    ]
