# Generated by Django 5.2 on 2025-04-25 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='meshroom_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file_format',
            field=models.CharField(choices=[('glb', 'GLB'), ('gltf', 'GLTF'), ('other', '기타')], default='glb', max_length=10),
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_images', to='model3d.model3d')),
            ],
            options={
                'db_table': 'model_source_images',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ModelTexture',
        ),
    ]
