# Generated by Django 5.2 on 2025-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0002_model3d_description_model3d_meshroom_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='model_url',
            field=models.FileField(upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='models/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='image_url',
            field=models.ImageField(upload_to='models/sources/'),
        ),
    ]
